# Generated by Django 2.1.2 on 2018-12-20 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=32, verbose_name='用户组')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_test.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='usergroup2',
            name='uObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_test.UserInfo'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user_group',
            field=models.ManyToManyField(to='app_test.UserInfo'),
        ),
        migrations.AddField(
            model_name='adddata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_test.UserInfo'),
        ),
    ]
