# Generated by Django 2.1.3 on 2018-12-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='UserData',
        ),
    ]
