# Generated by Django 2.1.3 on 2018-12-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0003_auto_20181208_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='userData',
            new_name='user',
        ),
    ]
