# Generated by Django 2.1.3 on 2018-12-08 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0004_auto_20181208_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=32, verbose_name='用户组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_test.UserInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
