# Generated by Django 2.1.3 on 2018-12-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0005_auto_20181208_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user_group',
            field=models.ManyToManyField(to='app_test.UserInfo'),
        ),
    ]
