# Generated by Django 2.1.3 on 2018-12-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0006_auto_20181208_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='user_group',
            field=models.ManyToManyField(null=True, to='app_test.UserInfo'),
        ),
    ]
